os:
  - linux
  - osx
language: c
env:
  # These are supposed to match ALL in makefile.
  # Each job builds 15 simulators.
  - SIM="pdp1 pdp4 pdp6 pdp7 pdp8 pdp9 pdp10 pdp10-ka pdp10-ki pdp11 pdp15 vax microvax3900 microvax1 rtvax1000"
  - SIM="microvax2 vax730 vax750 vax780 vax8200 vax8600 microvax2000 infoserver100 infoserver150vxt microvax3100 microvax3100e vaxstation3100m30 vaxstation3100m38 vaxstation3100m76 vaxstation4000m60"
  - SIM="microvax3100m80 vaxstation4000vlc infoserver1000 nova eclipse hp2100 hp3000 i1401 i1620 s3 altair altairz80 gri i7094 ibm1130"
  - SIM="id16 id32 sds lgp h316 cdc1700 swtp6800mp-a swtp6800mp-a2 tx-0 ssem b5500 isys8010 isys8020 isys8030 isys8024"
  - SIM="imds-210 imds-220 imds-225 imds-230 imds-800 imds-810"
  - SIM="scelbi 3b2 i701 i704 i7010 i7070 i7080 i7090 sigma uc15"
sudo: required
install: sh -ex .travis/deps.sh
script: make $SIM
notifications:
  email:
    recipients:
      - Mark@infocomm.com
      - lars@nocrew.org
